### ISSUE TITLE
Post Body Array Issue

### ISSUE THREAD

**Issue by tianp** [ciaranj/node-oauth#122]
I try to do the POST, and this is the example body: 

key_a: "value a",
key_b[0] : "value b 0",
key_b[1]: "value b 1"
 
I try to debug, and in the _performSecureRequest method, the post body become like this:

key_a=value%20a&key_b=&key_b=

The value in key_b is lost. Any options?

**Comment by bertop89** [comment]
Are you using JSON?

**Comment by tianp** [comment]
No, I'm not using JSON. I did some workaround to fix this. However, this is a very old thread and I'm closing this. Feel free to reopen.
