### ISSUE TITLE
201 Response to Post request treated like an error?

### ISSUE THREAD

**Issue by mdausmann** [ciaranj/node-oauth#141]
I am trying to use your native _request method to post data to a protected resource.  My wrapper function looks something like this...

    var OAuth = require('oauth').OAuth2
    exports.oAuthPost = function(req, res, accessToken, pathToResource, dataToPost){
      var _oAuth = new OAuth(..etc..); 

      var body = JSON.stringify(dataToPost);

      var post_headers =  {"Content-Type": "application/json","Content-Length": body.length};

      _oAuth._request("POST", pathToResource, post_headers, body, accessToken, function (error, result, response) {
        if(error) {
          res.json({error: error});
        } else {
          res.send(201, 'resource created ok!');
        }
      });
    };

When the endpoint sends back a perfectly good 201 response, the _request method treats it like an error because the following code from oAuth...

      if( response.statusCode != 200 && (response.statusCode != 301) && (response.statusCode != 302) ) {
        callback({ statusCode: response.statusCode, data: result });
      } else {
        callback(null, result, response);
      }

doesn't recognise 201 as a 'valid' response.  Am I missing something?  should I use a different method for posting?  Have I got the callback signature wrong?

Michael

**Comment by ciaranj** [comment]
Not any more (fixed in eefd821)
