### ISSUE TITLE
createCredentials() is deprecated, use tls.createSecureContext instead

### ISSUE THREAD

**Issue by babsonmatt** [ciaranj/node-oauth#196]
node 0.11.13 gives the following warning:

`createCredentials() is deprecated, use tls.createSecureContext instead`

Thanks!

**Comment by coolaj86** [comment]
bump

**Comment by demisx** [comment]
This fix doesn't appear to be in master yet. Or, am I missing something? We are still seeing this deprecation error.

**Comment by coolaj86** [comment]
I think that's dead code anyway, isn't it? I remember looking at it and that var isn't even ever used.

**Comment by ciaranj** [comment]
It is dead code, but the message is annoying a bunch of people, I've just not merged a fix yet (life has been crazy recently :( )

**Comment by demisx** [comment]
@ciaranj When you get a chance, mate. There are other projects on top of this one where this message pops up as well. Cheers.
