### ISSUE TITLE
please bump npm package

### ISSUE THREAD

**Issue by neofreko** [ciaranj/node-oauth#238]
fix for #196 is not in the npm registry yet. All oauth-based passport packages that I've tried these past few days are spewing the same error message:
````
createCredentials() is deprecated, use tls.createSecureContext instead
````
Let's save some souls from headache.

Temporary fix is by forking parent package and update oauth dependency to:
````
"oauth": "git://github.com/ciaranj/node-oauth"
````

よろしくお願いします!

**Comment by r3trosteve** [comment]
Urgh. Clunk. Head hits table.

I'm getting this too. Is there any update?

**Comment by VanessaHenderson** [comment]
If you actually look into the code on this repo, auth2.js still uses the createCredentials method. On the 18th Decemeber, 2014 @ciaranj put the line back in that refers to the method.
In the fix #196 that @neofreko mentioned simply removed the line because it was unused. I don't know why it was put back in... I'm guessing it might have been a merge mishap.

**Comment by ciaranj** [comment]
Seems reasonable that I screwed up.  My life is currently a little upside down dealing with some premature twins :/ sorry, when I get a chance I'll sort it!

**Comment by powdahound** [comment]
:+1:

**Comment by lucidtech** [comment]
bump

**Comment by monbro** [comment]
+1

**Comment by ohmslaw** [comment]
+1

**Comment by kulakowka** [comment]
I have this error too...

**Comment by EgoAleSum** [comment]
+1

**Comment by basickarl** [comment]
+1

**Comment by winduptoy** [comment]
+1

**Comment by joeonmars** [comment]
+1

**Comment by GregTurner** [comment]
+1

**Comment by Apercu** [comment]
+1

**Comment by mid0111** [comment]
:+1:

**Comment by VanessaHenderson** [comment]
@ciaranj think you could bump it soon? Looks like lots of people need it bumped...

**Comment by mstampfli** [comment]
+1

**Comment by mvach** [comment]
+1

**Comment by mhmeadows63** [comment]
+1

**Comment by tiddan** [comment]
+1

**Comment by scottsmeester** [comment]
Yo - +1

**Comment by dasinf** [comment]
+1

**Comment by lgabster** [comment]
me to

**Comment by ajitpawar** [comment]
+1

**Comment by danazkari** [comment]
+1

**Comment by thessler27** [comment]
+1

**Comment by alesscor** [comment]
+1

**Comment by DoryZi** [comment]
+1

**Comment by jjtortosa** [comment]
+1

**Comment by akuz** [comment]
+1

**Comment by pshoemaker39** [comment]
+1

**Comment by tattivitorino** [comment]
+1 any news on this? can anyone tell me how to fix this? plus, I dont know whether it is related to this warning, but using passport-facebook the profile object comes back undefined!

**Comment by kellyrmilligan** [comment]
+1?

**Comment by zloyded** [comment]
+1

**Comment by bjackson** [comment]
any timetable for this?

**Comment by gutsal-arsen** [comment]
+1

**Comment by ggarber** [comment]
+1

**Comment by aoberoi** [comment]
:+1:

**Comment by edwardvalentini** [comment]
+1 please

**Comment by gabrielbiga** [comment]
https://github.com/ciaranj/node-oauth/pull/244
This pull request solved for me

**Comment by tadman** [comment]
Would be really nice to see a fix for this merged, especially since there's a solution

**Comment by bjackson** [comment]
This project seems abandoned.

**Comment by tadman** [comment]
I'm here because it's used by various Oauth-based back-ends for [Passport](http://passportjs.org/).

**Comment by ciaranj** [comment]
'Funny' story I finally found a spare moment between feeding ill babies to push a fix (twins are hard) and npm seems knackered: 

![image](https://cloud.githubusercontent.com/assets/55368/7660097/fa5a84e2-fb3e-11e4-8e2f-c2ad1401c7c2.png)

Not really sure how to proceed :/

**Comment by ciaranj** [comment]
huh. weird. It worked anyway!

**Comment by lianyi** [comment]
+1
