### ISSUE TITLE
"No Access-Control-Allow-Origin" when using node-auth in browserify

### ISSUE THREAD

**Issue by shankie-san** [ciaranj/node-oauth#266]
I've had node-oauth working nicely in a node/express environment, but now I'm trying to integrate it into a single page app using browserify. Using the same API endpoints that worked correctly, I'm getting the following error in dev tools:

```
Fetch API cannot load http://mytestapi.com. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 400
```

This might well be related to [this issue](https://github.com/ciaranj/node-oauth/issues/243) as the problem might well go away if I could set the Access-Control-Allow-Origin header to "*"

**Comment by YurkinPark** [comment]
It seems like module was created to work with https://github.com/substack/http-browserify but it is outdated replaced by https://www.npmjs.com/package/stream-http . There is the same method which generates request object, but API is different.

**Comment by shankie-san** [comment]
I'm going to close this issue as it's so old that it might as well have been a different human who opened this! 😉
