### ISSUE TITLE
oauth_problem=version_rejected

### ISSUE THREAD

**Issue by UlyssesAlves** [ciaranj/node-oauth#271]
I am getting this error message, "oauth_problem=version_rejected" when I try to get the Request Token from Magento.

The Magento documentation says this error occurs when the version number is different than "1.0a". I have checked to see if it was with a different value, but no. It's properly set to "1.0a", still the server gives me this error response.

Here is my code:

    module.exports.obtenhaAutorizacaoOAuth = function(req, res, next) {
	var integracao = req.body;

	var urlPaginaDeConfiguracaoDaIntegracao = req.headers.host + '/painel/#/integracao';

	var parametrosOAuth = {
		requestTokenUrl: '',
		accessTokenUrl: '',
		authorizeUrl: '',
		consumerKey: integracao.ecommerce.consumerKey,
		consumerSecret: integracao.ecommerce.consumerSecret,
		authorize_callback: urlPaginaDeConfiguracaoDaIntegracao,
	};

	switch (integracao.ecommerce.plataforma) {
		case 'Magento':
			parametrosOAuth.requestTokenUrl = integracao.ecommerce.dominio + 'oauth/initiate';
			parametrosOAuth.accessTokenUrl = integracao.ecommerce.dominio + 'oauth/token';
			parametrosOAuth.authorizeUrl = integracao.ecommerce.dominio + 'oauth/authorize';
		break;
	}

	var oauth = new OAuth(
      parametrosOAuth.requestTokenUrl,
      parametrosOAuth.accessTokenUrl,
      parametrosOAuth.consumerKey,
      parametrosOAuth.consumerSecret,
      "1.0a", // VERSION IS PASSED AS EXPECTED BY MAGENTO DOCUMENTATION.
      null,
      'HMAC-SHA1'
    );

		oauth.getOAuthRequestToken(function(error, oauth_token, oauth_token_secret, results){
		  if (error) { // THIS ERROR OBJECT IS FILLED WITH THE MESSAGE "oauth_problem=version_rejected"
		  	console.log('error :' + error);
		  } else { 
		    console.log('oauth_token :' + oauth_token);
		    console.log('oauth_token_secret :' + oauth_token_secret);
		    console.log('requestoken results :' + util.inspect(results));
		    console.log("Requesting access token");

		    oauth.getOAuthAccessToken(oauth_token, oauth_token_secret, function(error, oauth_access_token, oauth_access_token_secret, results2) {
		      console.log('oauth_access_token :' + oauth_access_token)
		      console.log('oauth_token_secret :' + oauth_access_token_secret)
		      console.log('accesstoken results :' + util.inspect(results2))
		      console.log("Requesting access token")
		      var data= "";

		      oauth.getProtectedResource("http://term.ie/oauth/example/echo_api.php?foo=bar&too=roo", "GET", oauth_access_token, oauth_access_token_secret,  function (error, data, response) {
		          console.log(data);
		      });
		    });
		  }
		});  
};

**Comment by trong-le** [comment]
If you haven't fixed it yet, getting rid of the 'a' in the '1.0a' should fix it. Worked for me.
