### ISSUE TITLE
"The header content contains invalid characters" exception being thrown

### ISSUE THREAD

**Issue by siboulet** [ciaranj/node-oauth#296]
Hi,

I started having "The header content contains invalid characters" exception being thrown. When doing an OAuth request, the error callback is being called with the error, but also an exception is being thrown.

```js
TypeError: The header content contains invalid characters
at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
at new ClientRequest (_http_client.js:79:14)
at Object.exports.request (http.js:31:10)
at exports.OAuth2._executeRequest (/app/node_modules/oauth/lib/oauth2.js:132:30)
at exports.OAuth2._request (/app/node_modules/oauth/lib/oauth2.js:111:8)
at exports.OAuth2.get (/app/node_modules/oauth/lib/oauth2.js:213:8)
...
```

I *think* it might be related to some recent changes in Node.JS HTTP module being more strict about HTTP headers.

This is probably due to remote end having some invalid headers, but it's not very convenient to have the exception thrown and the error should probably be handled in the callback.

I think we need to wrap the request call in try/catch block here: https://github.com/ciaranj/node-oauth/blob/master/lib/oauth2.js#L132

Similar to https://github.com/request/request/pull/2164

Node.Js 4.4.0
node-oauth 0.9.14

**Comment by siboulet** [comment]
After further investigation it turned out access_token was undefined in my oauth.get() call, which caused the exception to be thrown. Properly passing access_token and the exception goes away.

**Comment by sebilasse** [comment]
@siboulet How about closing this issue? 
You should be able to do it yourself because you are the author ...
