### ISSUE TITLE
sample for facebook?

### ISSUE THREAD

**Issue by rlynjb** [ciaranj/node-oauth#315]
Hi guys, i was wondering if there is a sample code for facebook? i'm pretty new to oauth and i can seem to find a sample one out there

**Comment by dman777** [comment]
[This is an excellent tutorial with example. A little dated but still good](https://medium.com/@TheBigFatNoob/working-on-facebooks-graph-api-using-node-js-4bd107ad8c61#.uezyhv5gd)

**Comment by rlynjb** [comment]
thank you @dman777
